from pathlib import Path

import pytest

from genframes.data import (
    DatasetManifest,
    DatasetRole,
    RiskLevel,
    SampleRecord,
    SourceRecord,
    Split,
    assign_split,
)


def _manifest() -> DatasetManifest:
    return DatasetManifest(
        name="tiny",
        created_at="2026-08-24T00:00:00Z",
        sources=(
            SourceRecord(
                source_id="synthetic-v1",
                name="Synthetic V1",
                canonical_url="generated://genframes/analytic-v1",
                retrieved_at="2026-08-24T00:00:00Z",
                archive_sha256=None,
                dataset_license="MIT",
                content_license="MIT",
                roles=(DatasetRole.TRAIN, DatasetRole.VALIDATION),
                risk=RiskLevel.GREEN,
                risk_reason="Generated by GenFrames",
            ),
        ),
        samples=(
            SampleRecord(
                sample_id="sample-1",
                source_id="synthetic-v1",
                sequence_id="sequence-1",
                split=Split.TRAIN,
                frame_paths=("000.png", "001.png", "002.png"),
                frame_times=(0.0, 0.25, 1.0),
                input_indices=(0, 2),
                target_index=1,
                source_fps=4.0,
                width=32,
                height=24,
            ),
        ),
    )


def test_manifest_round_trip(tmp_path: Path) -> None:
    path = tmp_path / "manifest.json"
    expected = _manifest()
    expected.save(path)
    assert DatasetManifest.load(path) == expected
    assert expected.samples[0].target_time == pytest.approx(0.25)


def test_split_assignment_is_sequence_stable() -> None:
    assert assign_split("source/clip-1") == assign_split("source/clip-1")


def test_invalid_temporal_order_is_rejected() -> None:
    sample = _manifest().samples[0]
    invalid = SampleRecord(**{**sample.__dict__, "frame_times": (0.0, 1.0, 0.5)})
    with pytest.raises(ValueError, match="strictly increasing"):
        invalid.validate()

